### ISSUE TITLE
In Windows, when we do 'vagrant provision' in ;layers/web, we get error as in description

### ISSUE THREAD

**Issue by dasari234** [rajasoun/dev.box#5]
```
{ web } master » vagrant provision                                                                                                              /cygdrive/c/Users/Workspace/B2B/dev.box/layers/web
==> web: Running provisioner: ansible...
Windows is not officially supported for the Ansible Control Machine.
Please check https://docs.ansible.com/intro_installation.html#control-machine-requirements
    web: Running ansible-playbook...
zsh:cd:1: no such file or directory: --connection=ssh
sed: -e expression #1, char 41: unterminated address regex
Traceback (most recent call last):
  File "/home/srinidas/ansible/bin/ansible-playbook", line 43, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 133, in <module>
    p, CONFIG_FILE = load_config_file()
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 129, in load_config_file
    raise AnsibleOptionsError("Error reading config file: \n{0}".format(e))
ansible.errors.AnsibleOptionsError: Error reading config file:
File contains no section headers.
file: /cygdrive/c/Users/Workspace/B2B/dev.box/layers/web/ansible.cfg, line: 1
'../../ansible/ansible.cfg'
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Then we did:
```
{ web } master » ansible --version                                                                                                            /cygdrive/c/Users/Workspace/B2B/dev.box/layers/web 1
Traceback (most recent call last):
  File "/home/srinidas/ansible/bin/ansible", line 43, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 133, in <module>
    p, CONFIG_FILE = load_config_file()
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 129, in load_config_file
    raise AnsibleOptionsError("Error reading config file: \n{0}".format(e))
ansible.errors.AnsibleOptionsError: Error reading config file:
File contains no section headers.
file: /cygdrive/c/Users/Workspace/B2B/dev.box/layers/web/ansible.cfg, line: 1
'../../ansible/ansible.cfg'
```

**Comment by rcramu** [comment]
An observation:
This issue happens, even if the system recognizes the ansible software in babun, after executing 'setup_ansible.sh'  from 'scripts'.

The moment you execute 'vagrant provision' from 'layers/web',  the mentioned issue shows up.
